# Generated by Django 2.1 on 2020-07-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.CharField(max_length=255),
        ),
    ]
