# Generated by Django 2.1 on 2020-07-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200727_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(related_name='users', to='movies.Movie'),
        ),
    ]
