# Generated by Django 3.0.8 on 2020-10-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200727_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='salam', max_length=255),
        ),
    ]
